services:
  mysql:
    image: mysql:8.0
    container_name: challenge-forum-hub-mysql-db
    environment:
      MYSQL_DATABASE: challenge_forum_hub
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
