CREATE TABLE usuario
(
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    login        VARCHAR(100) NOT NULL UNIQUE,
    senha        VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);